version: '3'

services:

  db:
 
    container_name: db
    hostname: ${POSTGRES_HOST}
    # загрузка переменных среды
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./docker/postgres.Dockerfile
    # монтирование локальной папки ./db в доккер в каталог постгресс данных
    # причем, если ./db уже содержит файлы базы, то скрипт развертывания не будет накатываться
    # скрипт развертывания 202304050315_init_deploy.sql накатывается в ./docker/postgres.Dockerfile
    volumes:
      - ./db:/var/lib/postgresql/data
    # пробрасывания порта базы из доккера из переменной среды
    ports:
      - ${POSTGRES_EXTERMAL_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    # запуск постгресса с кастомным конфигом
    # так нужно сделать, чтобы запустить отладчик постгресса
    # а также переопределить порт
    # сам отладчик устанавливается и настраивается в ./docker/postgres.Dockerfile
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      # это задание предопределенных переменных в образе
      # образ создаст нужную бд, пользователя с паролем
      # см документацию: https://hub.docker.com/_/postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # стандартная переменная среды, откуда постгрес берет порт
      # если он не задан, то 5432 по умолчанию
      PGPORT: ${POSTGRES_PORT}
    healthcheck:
      test: "exit 0"
  
  app:

    container_name: app
    hostname: app
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./docker/python.Dockerfile
    # прокидывание портов
    ports:
     - ${PYTHON_EXTERNAL_PORT}:${PYTHON_PORT}
    restart: unless-stopped
    depends_on:
      - db
